"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, CheckCircle2, Database, Flag, HardDrive, RefreshCw, RotateCcw, Server, XCircle } from "lucide-react";
import { useState } from "react";
import { ErrorState, LoadingState } from "@/components/query-state";
import { StatusBadge } from "@/components/status-badge";
import { api, ApiError } from "@/lib/api";
import { useAuth } from "@/providers/auth-provider";

interface Health { status: string; components: Record<string, string>; timestamp: string }
interface AuditLog { id: string; action: string; entityType: string; entityId: string | null; beforeValue: unknown; afterValue: unknown; reason: string | null; requestId: string; ipAddress: string | null; createdAt: string; actor: { publicId: string; fullName: string } | null }
interface Failure { id: string; queueName: string; jobId: string; jobName: string; errorCode: string | null; errorMessage: string; failedAt: string; resolvedAt: string | null; retryCount: number }
interface MessageReport { id: string; reason: string; status: string; reviewNote: string | null; createdAt: string; reportedBy: { publicId: string; fullName: string }; reviewedBy: { publicId: string; fullName: string } | null; message: { id: string; body: string; createdAt: string; sender: { publicId: string; fullName: string }; conversation: { id: string; title: string | null; type: string } } }
interface Page<T> { data: T[]; meta: { page: number; pageSize: number; total: number; pageCount: number } }

export default function OperationsPage() {
  const { user } = useAuth();
  const client = useQueryClient();
  const canHealth = Boolean(user?.permissions.includes("system.health"));
  const canAudit = Boolean(user?.permissions.includes("audit.read"));
  const canJobs = Boolean(user?.permissions.includes("notifications.retry"));
  const canModerate = Boolean(user?.permissions.includes("messages.moderate_reported"));
  const [auditPage, setAuditPage] = useState(1);
  const [filters, setFilters] = useState({ action: "", entityType: "", actor: "" });
  const [reportStatus, setReportStatus] = useState("OPEN");
  const [reviewNotes, setReviewNotes] = useState<Record<string, string>>({});
  const queryString = new URLSearchParams({ page: String(auditPage), pageSize: "25", ...(filters.action ? { action: filters.action } : {}), ...(filters.entityType ? { entityType: filters.entityType } : {}), ...(filters.actor ? { actor: filters.actor } : {}) }).toString();
  const health = useQuery({ queryKey: ["system-health"], queryFn: () => api.health<Health>("ready"), enabled: canHealth, retry: false });
  const audit = useQuery({ queryKey: ["audit-logs", auditPage, filters], queryFn: () => api.get<Page<AuditLog>>(`/audit-logs?${queryString}`), enabled: canAudit });
  const jobs = useQuery({ queryKey: ["background-jobs"], queryFn: () => api.get<Page<Failure>>("/background-jobs?resolved=false&pageSize=50"), enabled: canJobs, refetchInterval: 10_000 });
  const reports = useQuery({ queryKey: ["message-reports", reportStatus], queryFn: () => api.get<MessageReport[]>(`/message-reports?status=${reportStatus}`), enabled: canModerate });
  const retry = useMutation({ mutationFn: (id: string) => api.post(`/background-jobs/${id}/retry`), onSuccess: () => void client.invalidateQueries({ queryKey: ["background-jobs"] }) });
  const resolve = useMutation({ mutationFn: (id: string) => api.post(`/background-jobs/${id}/resolve`), onSuccess: () => void client.invalidateQueries({ queryKey: ["background-jobs"] }) });
  const moderate = useMutation({ mutationFn: ({ id, status }: { id: string; status: "REVIEWED" | "DISMISSED" | "ACTIONED" }) => api.patch(`/message-reports/${id}`, { status, note: reviewNotes[id]?.trim() || undefined }), onSuccess: () => void client.invalidateQueries({ queryKey: ["message-reports"] }) });
  const actionError = retry.error ?? resolve.error ?? moderate.error;

  return <>
    <div className="page-heading"><div><span className="eyebrow">Administration</span><h1 className="page-title" style={{ marginTop: 6 }}>Audit & operations</h1><p className="page-subtitle">Dependency health, append-only activity history and failed background work.</p></div></div>
    {actionError && <div className="error-box" style={{ marginBottom: 16 }}>{actionError instanceof ApiError ? actionError.message : actionError.message}</div>}
    {canHealth && <section className="card" style={{ padding: 20, marginBottom: 18 }}><div className="section-head"><div><h2>System readiness</h2><p>Live checks against required infrastructure</p></div><button className="icon-button" aria-label="Refresh system health" onClick={() => void health.refetch()}><RefreshCw size={18} /></button></div>
      {health.isLoading ? <LoadingState /> : health.isError ? <div className="error-box"><XCircle size={18} /> One or more dependencies are unavailable. Check the API logs for the protected readiness detail.</div> : health.data && <div className="metric-grid">{Object.entries(health.data.components).map(([name, status]) => { const Icon = name === "postgres" ? Database : name === "objectStorage" ? HardDrive : Server; return <article className="card metric-card" key={name}><span className="metric-icon" style={{ color: status === "up" ? "#16a34a" : "#dc2626", background: status === "up" ? "#f0fdf4" : "#fff1f2" }}><Icon size={20} /></span><div><span className="muted">{name.replace(/([A-Z])/g, " $1")}</span><strong style={{ fontSize: 18 }}>{status.toUpperCase()}</strong></div></article>; })}</div>}
    </section>}

    {canJobs && <section className="card" style={{ padding: 20, marginBottom: 18 }}><div className="section-head"><div><h2>Failed background jobs</h2><p>Tenant-scoped failures that still require operator attention</p></div><button className="icon-button" aria-label="Refresh failed jobs" onClick={() => void jobs.refetch()}><RefreshCw size={18} /></button></div>
      {jobs.isLoading ? <LoadingState /> : jobs.isError ? <ErrorState /> : jobs.data?.data.length ? <div style={{ overflowX: "auto" }}><table className="data-table"><thead><tr><th>Queue</th><th>Failure</th><th>Attempts</th><th>Failed</th><th>Actions</th></tr></thead><tbody>{jobs.data.data.map((job) => <tr key={job.id}><td><strong>{job.queueName}</strong><br /><small className="muted">{job.jobName}</small></td><td>{job.errorMessage}</td><td>{job.retryCount}</td><td>{new Date(job.failedAt).toLocaleString()}</td><td><div className="button-row">{job.queueName === "notification-delivery" && <button className="btn" disabled={retry.isPending} onClick={() => retry.mutate(job.id)}><RotateCcw size={15} />Retry</button>}<button className="btn" disabled={resolve.isPending} onClick={() => resolve.mutate(job.id)}><CheckCircle2 size={15} />Resolve</button></div></td></tr>)}</tbody></table></div> : <div className="empty"><CheckCircle2 size={22} /> No unresolved background failures.</div>}
    </section>}

    {canModerate && <section className="card" style={{ padding: 20, marginBottom: 18 }}><div className="section-head"><div><h2>Reported messages</h2><p>Review college-scoped reports without exposing unrelated conversations</p></div><div className="button-row"><select aria-label="Reported message status" value={reportStatus} onChange={(event) => setReportStatus(event.target.value)}><option value="OPEN">Open</option><option value="REVIEWED">Reviewed</option><option value="ACTIONED">Actioned</option><option value="DISMISSED">Dismissed</option></select><button className="icon-button" aria-label="Refresh reported messages" onClick={() => void reports.refetch()}><RefreshCw size={18} /></button></div></div>
      {reports.isLoading ? <LoadingState /> : reports.isError ? <ErrorState /> : reports.data?.length ? <div style={{ overflowX: "auto" }}><table className="data-table"><thead><tr><th>Report</th><th>Message</th><th>Conversation</th><th>Review</th></tr></thead><tbody>{reports.data.map((report) => <tr key={report.id}><td><strong>{report.reportedBy.fullName}</strong><br /><small className="muted">{new Date(report.createdAt).toLocaleString()}</small><p style={{ maxWidth: 320 }}>{report.reason}</p></td><td><strong>{report.message.sender.fullName}</strong><p style={{ maxWidth: 420, whiteSpace: "pre-wrap" }}>{report.message.body || "[deleted message]"}</p><small className="muted">{new Date(report.message.createdAt).toLocaleString()}</small></td><td>{report.message.conversation.title ?? report.message.conversation.type.replaceAll("_", " ")}</td><td>{reportStatus === "OPEN" ? <div style={{ minWidth: 270 }}><label className="field"><span>Moderator note (optional)</span><textarea rows={2} maxLength={1000} value={reviewNotes[report.id] ?? ""} onChange={(event) => setReviewNotes((notes) => ({ ...notes, [report.id]: event.target.value }))} /></label><div className="button-row" style={{ marginTop: 8 }}><button className="btn" disabled={moderate.isPending} onClick={() => moderate.mutate({ id: report.id, status: "REVIEWED" })}>Reviewed</button><button className="btn" disabled={moderate.isPending} onClick={() => moderate.mutate({ id: report.id, status: "ACTIONED" })}>Actioned</button><button className="btn" disabled={moderate.isPending} onClick={() => moderate.mutate({ id: report.id, status: "DISMISSED" })}>Dismiss</button></div></div> : <><StatusBadge value={report.status} />{report.reviewNote && <p>{report.reviewNote}</p>}<small className="muted">{report.reviewedBy?.fullName ?? "Moderator"}</small></>}</td></tr>)}</tbody></table></div> : <div className="empty"><Flag size={22} /> No {reportStatus.toLowerCase()} message reports.</div>}
    </section>}

    {canAudit && <section className="card" style={{ padding: 20 }}><div className="section-head"><div><h2>Audit trail</h2><p>Append-only administrative and workflow history</p></div><Activity size={20} /></div>
      <div className="form-grid" style={{ marginBottom: 16 }}><label className="field"><span>Action contains</span><input value={filters.action} onChange={(event) => { setAuditPage(1); setFilters((value) => ({ ...value, action: event.target.value })); }} placeholder="user.created" /></label><label className="field"><span>Entity type</span><input value={filters.entityType} onChange={(event) => { setAuditPage(1); setFilters((value) => ({ ...value, entityType: event.target.value })); }} placeholder="User" /></label><label className="field"><span>Actor name</span><input value={filters.actor} onChange={(event) => { setAuditPage(1); setFilters((value) => ({ ...value, actor: event.target.value })); }} placeholder="Name" /></label></div>
      {audit.isLoading ? <LoadingState /> : audit.isError ? <ErrorState /> : audit.data?.data.length ? <><div style={{ overflowX: "auto" }}><table className="data-table"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Entity</th><th>Reason / request</th><th>Change</th></tr></thead><tbody>{audit.data.data.map((entry) => <tr key={entry.id}><td>{new Date(entry.createdAt).toLocaleString()}</td><td>{entry.actor?.fullName ?? "System"}</td><td><StatusBadge value={entry.action} /></td><td>{entry.entityType}<br /><small className="muted">{entry.entityId ?? "—"}</small></td><td>{entry.reason ?? "—"}<br /><small className="muted">{entry.requestId}</small></td><td><details><summary>View</summary><pre style={{ maxWidth: 440, overflow: "auto", whiteSpace: "pre-wrap" }}>{JSON.stringify({ before: entry.beforeValue, after: entry.afterValue }, null, 2)}</pre></details></td></tr>)}</tbody></table></div><div className="button-row" style={{ justifyContent: "space-between", marginTop: 16 }}><button className="btn" disabled={auditPage <= 1} onClick={() => setAuditPage((page) => page - 1)}>Previous</button><span className="muted">Page {audit.data.meta.page} of {Math.max(1, audit.data.meta.pageCount)} · {audit.data.meta.total} entries</span><button className="btn" disabled={auditPage >= audit.data.meta.pageCount} onClick={() => setAuditPage((page) => page + 1)}>Next</button></div></> : <div className="empty">No audit entries match these filters.</div>}
    </section>}
  </>;
}
